"""initial neuroops schema

Revision ID: ae68e127a82b
Revises:
Create Date: 2026-08-11 00:48:35.220793
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ae68e127a82b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("data_type", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_datasets_data_type"), "datasets", ["data_type"], unique=False)
    op.create_index(op.f("ix_datasets_name"), "datasets", ["name"], unique=False)
    op.create_index(op.f("ix_datasets_status"), "datasets", ["status"], unique=False)
    op.create_table(
        "pipeline_configurations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pipeline_id", sa.String(length=100), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_configurations_pipeline_id"),
        "pipeline_configurations",
        ["pipeline_id"],
        unique=False,
    )
    op.create_table(
        "pipeline_definitions",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prediction_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("registered_model_name", sa.String(length=200), nullable=False),
        sa.Column("version_or_alias", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("input_payload", sa.JSON(), nullable=False),
        sa.Column("result_payload", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prediction_jobs_registered_model_name"),
        "prediction_jobs",
        ["registered_model_name"],
        unique=False,
    )
    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("column_count", sa.Integer(), nullable=True),
        sa.Column("schema_summary", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dataset_versions_dataset_id"), "dataset_versions", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_versions_fingerprint"), "dataset_versions", ["fingerprint"], unique=False
    )
    op.create_table(
        "experiments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("pipeline_id", sa.String(length=100), nullable=False),
        sa.Column("pipeline_config", sa.JSON(), nullable=False),
        sa.Column("model_ids", sa.JSON(), nullable=False),
        sa.Column("model_parameters", sa.JSON(), nullable=False),
        sa.Column("validation_strategy", sa.String(length=50), nullable=False),
        sa.Column("validation_config", sa.JSON(), nullable=False),
        sa.Column("primary_metric", sa.String(length=50), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("mlflow_parent_run_id", sa.String(length=100), nullable=True),
        sa.Column("prefect_flow_run_id", sa.String(length=100), nullable=True),
        sa.Column("winner_candidate_id", sa.String(length=36), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_experiments_dataset_id"), "experiments", ["dataset_id"], unique=False)
    op.create_index(
        op.f("ix_experiments_mlflow_parent_run_id"),
        "experiments",
        ["mlflow_parent_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiments_pipeline_id"), "experiments", ["pipeline_id"], unique=False
    )
    op.create_index(op.f("ix_experiments_status"), "experiments", ["status"], unique=False)
    op.create_index(
        op.f("ix_experiments_winner_candidate_id"),
        "experiments",
        ["winner_candidate_id"],
        unique=False,
    )
    op.create_table(
        "training_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("stage", sa.String(length=80), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("mlflow_run_id", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_runs_experiment_id"), "training_runs", ["experiment_id"], unique=False
    )
    op.create_index(
        op.f("ix_training_runs_mlflow_run_id"), "training_runs", ["mlflow_run_id"], unique=False
    )
    op.create_index(op.f("ix_training_runs_model_id"), "training_runs", ["model_id"], unique=False)
    op.create_table(
        "artifact_references",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("training_run_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("uri", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["training_run_id"], ["training_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artifact_references_training_run_id"),
        "artifact_references",
        ["training_run_id"],
        unique=False,
    )
    op.create_table(
        "model_candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("training_run_id", sa.String(length=36), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("artifact_uri", sa.Text(), nullable=True),
        sa.Column("is_winner", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["training_run_id"], ["training_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("training_run_id"),
    )
    op.create_index(
        op.f("ix_model_candidates_model_id"), "model_candidates", ["model_id"], unique=False
    )
    op.create_table(
        "registered_model_references",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("alias", sa.String(length=50), nullable=True),
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("model_uri", sa.Text(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["model_candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_registered_model_references_alias"),
        "registered_model_references",
        ["alias"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registered_model_references_candidate_id"),
        "registered_model_references",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registered_model_references_experiment_id"),
        "registered_model_references",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registered_model_references_name"),
        "registered_model_references",
        ["name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_registered_model_references_name"), table_name="registered_model_references"
    )
    op.drop_index(
        op.f("ix_registered_model_references_experiment_id"),
        table_name="registered_model_references",
    )
    op.drop_index(
        op.f("ix_registered_model_references_candidate_id"),
        table_name="registered_model_references",
    )
    op.drop_index(
        op.f("ix_registered_model_references_alias"), table_name="registered_model_references"
    )
    op.drop_table("registered_model_references")
    op.drop_index(op.f("ix_model_candidates_model_id"), table_name="model_candidates")
    op.drop_table("model_candidates")
    op.drop_index(op.f("ix_artifact_references_training_run_id"), table_name="artifact_references")
    op.drop_table("artifact_references")
    op.drop_index(op.f("ix_training_runs_model_id"), table_name="training_runs")
    op.drop_index(op.f("ix_training_runs_mlflow_run_id"), table_name="training_runs")
    op.drop_index(op.f("ix_training_runs_experiment_id"), table_name="training_runs")
    op.drop_table("training_runs")
    op.drop_index(op.f("ix_experiments_winner_candidate_id"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_status"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_pipeline_id"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_mlflow_parent_run_id"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_dataset_id"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_index(op.f("ix_dataset_versions_fingerprint"), table_name="dataset_versions")
    op.drop_index(op.f("ix_dataset_versions_dataset_id"), table_name="dataset_versions")
    op.drop_table("dataset_versions")
    op.drop_index(op.f("ix_prediction_jobs_registered_model_name"), table_name="prediction_jobs")
    op.drop_table("prediction_jobs")
    op.drop_table("pipeline_definitions")
    op.drop_index(
        op.f("ix_pipeline_configurations_pipeline_id"), table_name="pipeline_configurations"
    )
    op.drop_table("pipeline_configurations")
    op.drop_index(op.f("ix_datasets_status"), table_name="datasets")
    op.drop_index(op.f("ix_datasets_name"), table_name="datasets")
    op.drop_index(op.f("ix_datasets_data_type"), table_name="datasets")
    op.drop_table("datasets")
    # ### end Alembic commands ###
